### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by zhjygit** [perdragon/ARP_Hunter#1]
想学习一下这个项目，不过无法下载，可能是里面的东西太多了，下载到一半就失败了。能否将核心代码上传，其他发布的工程、exe之类的去除。谢谢了。

**Comment by perdragon** [comment]
感谢。我刚刚看了下，全部也就15M，几秒就下好了，可能是你的网络不好，建议重试就行了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: zhjygit<mailto:notifications@github.com>
发送时间: 2020年2月6日 11:50
收件人: perdragon/ARP_Hunter<mailto:ARP_Hunter@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [perdragon/ARP_Hunter] 无法下载 (#1)


想学习一下这个项目，不过无法下载，可能是里面的东西太多了，下载到一半就失败了。能否将核心代码上传，其他发布的工程、exe之类的去除。谢谢了。

―
